#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

load_config "$1"

[ "${second_stage-}" = 1 ] || second_stage=1 unshare_exec "$script" "$@"

shift

cgroup is_running || error "container is already running"

mount_base
mount_android_runtime

## share tmp
add_bind "$tmpdir" /tmp

for i in /sdcard /data/data/com.termux
do add_bind "$i" "$i"
done

switch_root
cgroup create attach

exec env -i TERM="$TERM" "$@"
