#!/data/data/com.termux/files/usr/bin/zsh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

load_config "$1"

echo "name: $cont_name"
echo "states:"
echo "    running: $(cgroup is_running)"
echo "processes:"
cgroup ps
