#!/bin/sh -eu

. "$(dirname "$(realpath "$0")")/COMMON"

require root

target="${1-}"; shift

first_stage()
{
	[ "$target" != "" ] || error "empty root"
	termux_chroot_second_stage=1 exec unshare -m -- "$script" "$@"
}

[ "${termux_chroot_second_stage-}" = 1 ] || first_stage "$(realpath "$target")" "$@"

## second stage

[ -d "$target" ] || error "root not a dir"
add_bind()
{
	src="$1"; dst="$2"; shift 2
	[ -d "$target/$dst" ] || mkdir -p "$target/$dst"
	mountpoint -q "$target/$dst" || mount "$@" -R "$src" "$target/$dst"
}

## self remount
add_bind "$target" "/" -o suid,dev
## linux & android runtime
for i in /proc /sys /dev /apex/com.android.runtime /linkerconfig /system /sdcard /data/data/com.termux
do add_bind "$i" "$i" #-r
done
## share tmp
add_bind "$TMPDIR" /tmp

cd "$target"
busybox pivot_root "$target" .
umount -l -f .
cd /

unset LD_PRELOAD
exec env -i -- "$@"
